name: VipManagement
version: 1.00
author: Trsak
main: cz.trsak.VipManagement.Main
description: Plugin for Vip Management.
permissions:
  vip.*:
    description: Allows to use all commands.
  vip.user:
    description: Allows to use all user commands.
  vip.admin:
    description: Allows to use all admin commands.
  vip.info:
    description: Allows to use /vip command.
  vip.reload:
    description: Allows to use /vip reload command.
  vip.gencode:
    description: Allows to use /vip gencode command.
  vip.codes:
    description: Allows to use /vip codes command.
  vip.code:
    description: Allows to use /vip code command.
  vip.time:
    description: Allows to use /vip time command.
commands:
  vip:
    description: All VIP Management commands.